### ISSUE TITLE
Maven broken

### ISSUE THREAD

**Issue by pasterp** [pasterp/kangourou#13]
> Erreur : impossible de trouver ou de charger la classe principale fr.imt.fa20.kangourou.Game
> Causé par : java.lang.ClassNotFoundException: fr.imt.fa20.kangourou.Game

**Comment by L0u15** [comment]
Oui la classe Game n'existe plus depuis ce week-end.
Tu as pullé la dernière version de master? 30min environ...

**Comment by pasterp** [comment]
Oui c'est pour ça que je créé cette issue ?

**Comment by L0u15** [comment]
je ne sais pas pourquoi tu as créé l'issue. Pourquoi me poses tu la question?

**Comment by pasterp** [comment]
Bah non mais l'issue date d'après le commit du coup pourquoi tu me demandes ?

**Comment by L0u15** [comment]
J'ai du mal à te comprendre.

**Comment by L0u15** [comment]
je suis sur master, rien a pusher, up to date et le jeu tourne. As tu juste ce message ou il y en a d'autre? C'est qui quand est appelé la classe Game?

modif: et je build sans problème.

C'est à l'exec ou au build que ça pète?

**Comment by pasterp** [comment]
Comme dit dans le titre, maven


On 20 Mar 2018 at 10:28, <L0u15 <notifications@github.com>> wrote:

je suis sur master, rien a pusher, up to date et le jeu tourne. As tu juste
ce message ou il y en a d'autre? C'est qui quand est appelé la classe Game?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pasterp/kangourou/issues/13#issuecomment-374530000>,
or mute
the thread

**Comment by L0u15** [comment]
Si j'ai bien compris, tu veux de l'aide pour résoudre ton bug?

**Comment by L0u15** [comment]
Là j'ai pas suffisamment d'info pour t'aider.  
Demande à Will ou Gildas. Bon courage

**Comment by MouiseLichel** [comment]
je peux voir ton pom ? 
tu utilises quel IDE ? 
ouvre la classe principale : game object.java je crois et lace à partir de là

**Comment by pasterp** [comment]
Le pom c'est celui de master et mon ide c'est la ligne de commande


On 20 Mar 2018 at 11:20 am, <William Jedrzejak <notifications@github.com>>
wrote:

je peux voir ton pom ?
tu utilises quel IDE ?
ouvre la classe principale : game object.java je crois et lace à partir de
là

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pasterp/kangourou/issues/13#issuecomment-374545476>,
or mute
the thread

**Comment by MouiseLichel** [comment]
faut changer la ligne du pom par le bon chemin alors
<main.class>fr.imt.fa20.kangourou.Game</main.class>

**Comment by MouiseLichel** [comment]
les 2 lignes, y'en a une identique à la fin aussi
