### ISSUE TITLE
Maven broken x2

### ISSUE THREAD

**Issue by pasterp** [pasterp/kangourou#19]
`[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/pascal/kangourou/src/main/java/fr/imt/fa20/kangourou/map/Map.java:[25,45] diamond operator is not supported in -source 1.6`

Dites vous tenter de le compiler le maven parfois ? Et/ou respecter ce qu'on a dit pour les versions de Java ?

**Comment by MouiseLichel** [comment]
![sans titre](https://user-images.githubusercontent.com/18681814/37897815-6d8e7564-30e7-11e8-97b6-1d1715aafee8.png)

**Comment by MouiseLichel** [comment]
C'est la seule fois ou on a parlé de version de java pour slick que j'ai pu retrouver ...

**Comment by pasterp** [comment]
Oui bah c'est pour ça que j'ai abandonné openjdk qui était le problème, j'ai pas changé la version vu que personne ne s'est plaint ?

**Comment by MouiseLichel** [comment]
J'avais expliqué comment le lancer avec openjdk, mais si tu as pris apache jdk c'est bon :) 

Peut être que personne n'a lancé avec maven, moi je me souviens avoir ajouté à mon projet éclipse une config pour qu'il prenne en compte la typo 1.8 avec les <> mais du coup j'ai pas changé le pom en effet.

je pense que c'est ces ligne qui décident de la version de java.
<maven.compiler.source>1.6</maven.compiler.source>
<maven.compiler.target>1.6</maven.compiler.target>
